# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 17:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=datetime.datetime(2018, 2, 10, 17, 58, 35, 824393))),
                ('client_id', models.CharField(max_length=256)),
                ('auth_token', models.CharField(default=b'2f5d3916-d7df-4d4c-abc6-600118f70bf6', max_length=512)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=254)),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254, null=True)),
                ('email', models.CharField(max_length=254)),
                ('dob', models.DateTimeField(null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], default=None, max_length=128)),
                ('profile_pic', models.CharField(max_length=512, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 2, 10, 17, 58, 35, 823901))),
            ],
        ),
        migrations.AddField(
            model_name='loginentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_models.User'),
        ),
    ]
